packages:
  - apps/*
  - packages/*
  - components/**
  - '!**/test/**'
  - utils/**

catalog:
  '@eslint/js': ^9.39.1
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vue/tsconfig': ^0.8.1
  axios: ^1.13.2
  element-plus: ^2.12.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^16.5.0
  react-router-dom: ^7.10.1
  typescript: ^5.9.3
  typescript-eslint: ^8.48.1
  unocss: ^66.5.10
  vite: ^7.2.6
  vite-plugin-vue-devtools: ^8.0.5
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.6
  unplugin-auto-import: ^20.3.0
  unplugin-vue-components: ^30.0.0

catalogs:
  ant-design:
    '@ant-design/icons': ^6.1.0
    '@ant-design/v5-patch-for-react-19': ^1.0.3
    antd: ^5.29.1
  react19:
    '@reduxjs/toolkit': ^2.11.0
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.1
    react: ^19.2.1
    react-dom: ^19.2.1
    react-redux: ^9.2.0
